name: Deploy Images to GHCR


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-store-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3.4.0
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GCHR_KEY}}

          - name: Bygg Docker-bildet
            run: docker build -t ghcr.io/steintokvam/portfolo-watch:latest .

          - name: Push Docker-bildet til GHCR
            run: docker push ghcr.io/steintokvam/portfolo-watch:latest



