name: Deploy Images to GHCR


on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
      push-gchr-image:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: './'
        steps:
          - name: 'Checkout GitHub Action'
            uses: actions/checkout@main

          - name: 'Login to GitHub Container Registry'
            uses: docker/login-action@v3.4.0
            with:
              registry: ghcr.io
              username: ${{github.actor}}
              password: ${{secrets.GCHR_KEY}}

          - name: 'Build Docker Image'
            run: docker buildx build --platform linux/arm64,linux/amd64 -t ghcr.io/steintokvam/portfolio-watch:latest .

          - name: 'Push image to GCHR'
            run: docker push ghcr.io/steintokvam/portfolio-watch:latest



